INSERT INTO emarket.categories (title,parentid,icon) VALUES
('Voiture, Moto & Camion',NULL,'0xe531')
,('Vélos & Accessoires',1,NULL)
,('Motos & Accessoires',1,NULL)
,('Camions & Accessoires',1,NULL)
,('Autres Voitures, Moto & Camion',1,NULL)
,('Voitures',1,NULL)
,('Pieces de voiture et pneu',1,NULL)
,('Electronique',NULL,'0xe325')
,('Téléphone',9,NULL)
,('Électromenager',9,NULL)
;
INSERT INTO emarket.categories (title,parentid,icon) VALUES
('Laptops & PCs',9,NULL)
,('Logiciel & Accessoires d´ordinateur',9,NULL)
,('Tablets',9,NULL)
,('TV',9,NULL)
,('Dépannage électronique',9,NULL)
,('Évènementiel',NULL,'0xe540')
,('Concert',18,NULL)
,('Mariage',18,NULL)
,('Anniversaire',18,NULL)
,('Accessoires de maison',18,NULL)
;
INSERT INTO emarket.categories (title,parentid,icon) VALUES
('Autres Évènementiel',18,NULL)
,('Prestation de service',NULL,'0xe8f9')
,('Restaurant',24,NULL)
,('Service traiteur',24,NULL)
,('Jobs',NULL,'0xe8f9')
,('Menagère',27,NULL)
,('Transport',27,NULL)
,('Gastronomie & Tourisme',27,NULL)
,('Construction',27,NULL)
,('Vente',27,NULL)
;
INSERT INTO emarket.categories (title,parentid,icon) VALUES
('Stage de vacances',27,NULL)
,('Santé',27,NULL)
,('Mecanicien',27,NULL)
,('Hôtesse',27,NULL)
,('Depannage',27,NULL)
,('Autres jobs',27,NULL)
,('Famille, Enfants & Bébé',NULL,'0xeb42')
,('Domestique & Babysitting',40,NULL)
,('Habits & Chaussures de bébés',40,NULL)
,('Habits & Chaussures d´enfants',40,NULL)
;
INSERT INTO emarket.categories (title,parentid,icon) VALUES
('Accessoires de Bébés',40,NULL)
,('Jeux pour Bébé',40,NULL)
,('Autres Famille, Enfant & Bébé',40,NULL)
,('Immobilier',NULL,'0xe88a')
,('Maison à louer',47,NULL)
,('Maison à vendre',47,NULL)
,('Terrain à louer',47,NULL)
,('Terrain à vendre',47,NULL)
,('Service de déménagement',47,NULL)
,('Autres immobilier',47,NULL)
;
INSERT INTO emarket.categories (title,parentid,icon) VALUES
('Don & Echanges',NULL,'0xe8f6')
,('Don',54,NULL)
,('Échange',54,NULL)
,('Livres & Film',NULL,'0xe431')
,('Roman',57,NULL)
,('Materiel scolaire',57,NULL)
,('Livres scolaires & academiques',57,NULL)
,('Autres Livres & Film',57,NULL)
,('Maison & Gardin',NULL,'0xe16b')
,('Objects pour salle de bain',62,NULL)
;
INSERT INTO emarket.categories (title,parentid,icon) VALUES
('Meubles de bureau',62,NULL)
,('Meubles de salon',62,NULL)
,('Meubles de chambre',62,NULL)
,('Decoration',62,NULL)
,('Lampe & éclairage',62,NULL)
,('Cours & Formation',NULL,'0xe80c')
,('Restauration & Patisserie',69,NULL)
,('Cours d´Informatik',69,NULL)
,('Cours de musique',69,NULL)
,('Cours de danse',69,NULL)
;
INSERT INTO emarket.categories (title,parentid,icon) VALUES
('Menuiserie',69,NULL)
,('Cours de langue',69,NULL)
,('Cours de répétition',69,NULL)
,('Cours d´Art',69,NULL)
,('Mode & Beauté',NULL,'0xe63d')
,('Vêtements de femmes',78,NULL)
,('Chaussures de femmes',78,NULL)
,('Vêtements d´hommes',78,NULL)
,('Chaussures d´hommes',78,NULL)
,('Autres Mode & Beauté',78,NULL)
;
INSERT INTO emarket.categories (title,parentid,icon) VALUES
('Bijoux & Accessoires',78,NULL)
,('Décoration',24,NULL)
,('Jeux & Loisirs',NULL,'0xeb48')
,('Jeux vidéos',86,'NULL')
,('Autres',NULL,'0xe5d3')
,('Bricollage',88,NULL)
,('Sport & Fitness',88,NULL)
,('Art & Musique',88,NULL)
;